Updated front-end
csun-metalab/profile-manager pull request #1
Opened 2018-08-22 17:22 UTC by Tiffufu

### Changes
- Pretty much everything in terms of styling
- Made different sections of app responsive
- Styled using Metaphor 2 framework.

## To test
- Click around the app and play with responsiveness to see if nothing gets weird.

## Note
- The META+LAB footer will be added by the end of the week, since I am waiting for an update for Metaphor 2 where it is included.
- Currently using a placeholder image

2018-08-27 18:02 UTC, andrewMETALAB requested changes
Everything looks great. I left a couple comments throughout the code, but it's all pretty minor. 

One other thing... do you think we should center the login screen instead of having it left-aligned?

2018-08-27 18:02 UTC, andrewMETALAB commented on resources/views/pages/login/index.blade.php
> +    <h1 class="h1__login">Student Log In</h1>
Consider using ".my-5" instead of this custom class (it achieves the same thing)

2018-08-27 18:02 UTC, andrewMETALAB commented on resources/assets/js/components/LoginForm.vue
> +                <div class="col-md-4">
For both inputs, you might want to wrap div class="col-md-4" in a div class="row" to account for the extra horizontal spacing on these inputs

2018-08-27 18:02 UTC, andrewMETALAB commented on resources/assets/js/components/LoginForm.vue
> +                    <label for="username" class="form-control--required">Username or Email</label>
I love the way that this class adds an asterisk using :after, but lets name it .form-label--required instead of .form-control--required (as .form-control is a bootstrap class for inputs, not labels)

2018-08-27 18:02 UTC, andrewMETALAB commented on resources/assets/js/components/InfoForm.vue
> +                <h2 class="text-center display-name">{{ this.user.display_name }}</h2>
consider renaming this class from .display-name to .profile-name in order to keep naming conventions consistent on this page (or rename .profile-avatar / .profile-img to .display-avatar / .display-img)

2018-08-27 18:02 UTC, andrewMETALAB commented on resources/assets/js/components/InfoForm.vue
> +                <a href="#" class="profile-avatar profile-img" @click.prevent="editImage">
Can we merge the classes of .profile-avatar and .profile-img into 1? Unless there is a reason that they are separated?

2018-08-29 17:44 UTC, Tiffufu commented on resources/assets/js/components/InfoForm.vue
> +                <a href="#" class="profile-avatar profile-img" @click.prevent="editImage">
Why do you make so much sense? Merged the two and everything worked out fine.

2018-08-29 20:10 UTC, andrewMETALAB approved these changes

2018-10-09 21:35 UTC, luisjg approved these changes
👍

2018-10-15 15:58 UTC, merged